### ISSUE TITLE
How to install Twee2 on WSL2

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [avapoet/twee2#58]
1. apt-get install ruby ruby-dev libxml2 libxml2-devel zlib zlib1g-dev
2. gem install twee2

Mind you I do a lot of dev work so I could have somethings already installed that I didn't know about.

**Comment by neonpixii** [comment]
some of the package names here are incorrect and will make the first install fail, at least on our computer. if this happens, try:

`sudo apt-get install ruby ruby-dev libxml2 libxml2-dev zlib1g zlib1g-dev`
